### ISSUE TITLE
Bug report: `cfg.merge_from_file("experiment.yaml")`

### ISSUE THREAD

**Issue by zc-alexfan** [rbgirshick/yacs#24] opened 2019-05-12 23:20 UTC
If the YAML file has repeated "parent" tag, YACS only merges the final set of parameters. For example, only the second list of HYPER are merged. 

~~~yaml
HYPER: 
    BATCH_SIZE: 10
SYS: 
    SOME_CONSTANT: 3
HYPER: 
   LEARNING_RATE: 1e-3
~~~

As a result, only `LEARNING_RATE: 1e-3` is applied.

**Comment by roytseng-tw** [comment] 2019-05-13 12:59
This is a duplicate issue of #17

**Comment by rbgirshick** [comment] 2019-05-13 14:14
Closing (duplicate of #17).

**Closed by rbgirshick** 2019-05-13 14:14 UTC
